[general]
library_name = "libimagequant"
output_file_path = "../src/generated_libimagequant.jl"
module_name = "LibImageQuantWrapper"
jll_pkg_name = "libimagequant_jll"
export_symbol_prefixes = []
show_c_function_prototype = true

[codegen]
use_ccall_macro = true
is_function_strictly_typed = true
